import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Search from '../components/Search'
import Card from '../components/Card'

import {getPosts,getTags,getPostByID} from '../lib/post'
export const  getServerSideProps = async({query}) =>{
    const posts = await getPosts(query.tag||'all')
    const tags = await getTags()
    return{
      props:{
        posts,
        tags
      }
    }
  }

  export default function Home({posts,tags}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sankalpa&apos;s Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className={styles.blog}>
        Sankalpa&apos;s Blog

      </h2>
      <div className={styles.sidemain}>
        <Search tags={tags} />
      </div>
      <div className={styles.cardholder}>
        {
          posts.map(post=>{
            return(
              <Card key={post.id} id={post.id} title={post.title} feature_image={post.feature_image}/>
            )
          })
        }
      </div>
      <div className="footer">
        Copyright @ Sankalpa
      </div>
    </div>
  )
}


